<?php

namespace Tests\Application\Gastos;

use App\Application\Gastos\GetGastosQueryHandler;
use App\Domain\Gastos\GastosRepository;
use App\Infrastructure\Gastos\InMemoryGastosRepository;
use PHPUnit\Framework\TestCase;
use Tests\Fixtures\GastosFixture;

class GetGastosQueryHandlerTest extends TestCase
{
    private GastosRepository $repository;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new GastosFixture();
    }

    public function testHandle()
    {
        $query = new GetGastosQueryHandler($this->repository);
        $result = $query->handle();
        $this->assertEquals(200, $result['code'], $result['message']);
        $totalDB = count($this->repository->getAll());
        $this->assertCount($totalDB, $result['data']);
    }

}
