<?php

namespace Tests\Application\Gastos;

use App\Application\Personas\CreatePersonaCommandHandler;
use App\Domain\Common\Conts\HttpStatusCode;
use App\Infrastructure\Gastos\InMemoryGastosRepository;
use App\Application\Gastos\GetGastosByPersonaQueryHandler;
use App\Infrastructure\Personas\InMemoryPersonasRepository;
use PHPUnit\Framework\TestCase;

class GetGastosByPersonaQueryHandlerTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new InMemoryGastosRepository();
        $this->personaRepository = new InMemoryPersonasRepository();
        $this->persona = $this->addPersona();
    }

    public function testHandler()
    {
        $query = new GetGastosByPersonaQueryHandler(
            $this->repository,
            $this->personaRepository,
        );
        $result = $query->handle($this->persona);
        $this->assertEquals(HttpStatusCode::OK, $result['code'], $result['message']);
    }

    public function testMustFailWhenPersonaDoesNotExist()
    {
        $query = new GetGastosByPersonaQueryHandler(
            $this->repository,
            $this->personaRepository,
        );
        $result = $query->handle(0);
        $this->assertEquals(HttpStatusCode::BAD_REQUEST, $result['code'], $result['message']);
    }

    private function addPersona()
    {
        $values = [];
        $values['apellido'] = 'Pankie';
        $values['nombre'] = 'Marcos';
        $values['apodo'] = 'El Pankie';
        $add = new CreatePersonaCommandHandler($this->personaRepository);
        $result = $add->handle($values);
        return $result['data'];
    }

}
