<?php

namespace Tests\Personas;

use App\Application\Personas\CreatePersonaCommandHandler;
use App\Domain\Personas\Persona;
use App\Domain\Personas\PersonasRepository;
use App\Infrastructure\Personas\InMemoryPersonasRepository;
use PHPUnit\Framework\TestCase;

class CreatePersonaCommandHandlerTest extends TestCase
{
    private PersonasRepository $repository;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new InMemoryPersonasRepository();
    }

    public function testHandle()
    {
        $values = [];
        $values['apellido'] = 'Pankie';
        $values['nombre'] = 'Marcos';
        $values['apodo'] = 'El Pankie';
        $add = new CreatePersonaCommandHandler($this->repository);
        $result = $add->handle($values);
        $this->assertEquals(201, $result['code'], $result['message']);
        $this->assertCount(1, $this->repository->getAll());
        $persona = $this->repository->findById($result['data']);
        $this->assertObjectValues($values, $persona);
    }

    private function assertObjectValues(array $values, ?Persona $newPersona): void
    {
        $this->assertEquals($values['apellido'], $newPersona->getApellido() );
        $this->assertEquals($values['nombre'], $newPersona->getNombre() );
        $this->assertEquals($values['apodo'], $newPersona->getApodo() );
    }

    public function testMustFailWhenApellidoIsEmpty(): void
    {
        $values = [];
        $values['apellido'] = '';
        $values['nombre'] = 'Marcos';
        $values['apodo'] = 'El Pankie';
        $add = new CreatePersonaCommandHandler($this->repository);
        $result = $add->handle($values);
        $this->assertEquals(500, $result['code'], $result['message']);
        $this->assertCount(0, $this->repository->getAll());
    }

    public function testMustFailWhenNombreIsEmpty(): void
    {
        $values = [];
        $values['apellido'] = 'Pankie';
        $values['nombre'] = '';
        $values['apodo'] = 'El Pankie';
        $add = new CreatePersonaCommandHandler($this->repository);
        $result = $add->handle($values);
        $this->assertEquals(500, $result['code'], $result['message']);
        $this->assertCount(0, $this->repository->getAll());
    }

}
