<?php

namespace Tests\Application\Personas;

use App\Application\Personas\GetPersonasQueryHandler;
use App\Infrastructure\Personas\InMemoryPersonasRepository;
use PHPUnit\Framework\TestCase;

class GetPersonasQueryHandlerTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new InMemoryPersonasRepository();
    }

    public function testHandle()
    {
        $query = new GetPersonasQueryHandler($this->repository);
        $result = $query->handle();
        $this->assertEquals(200, $result['code'], $result['message']);
    }

}
