<?php

namespace Tests\Application\Categorias;

use App\Application\Categorias\CreateCategoriaCommandHandler;
use App\Domain\Categorias\CategoriasRepository;
use App\Domain\Common\Conts\HttpStatusCode;
use App\Infrastructure\Categorias\InMemoryCategoriasRepository;
use PHPUnit\Framework\TestCase;

class CreateCategoriaCommandHandlerTest extends TestCase
{
    protected CategoriasRepository $repository;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new InMemoryCategoriasRepository();
    }

    public function testHandle()
    {
        $values = [];
        $values['descripcion'] = 'Categoria 1';
        $command = new CreateCategoriaCommandHandler($this->repository);
        $result = $command->handle($values);
        $this->assertEquals(HttpStatusCode::CREATED, $result['code'], $result['message']);
        $this->assertCount(1, $this->repository->getAll());
    }

    public function testMustFailWhenDescriptionIsEmpty()
    {
        $values['descripcion'] = '';
        $command = new CreateCategoriaCommandHandler($this->repository);
        $result = $command->handle($values);
        $this->assertEquals(HttpStatusCode::INTERNAL_SERVER_ERROR, $result['code'], $result['message']);
        $this->assertCount(0, $this->repository->getAll());
    }
}
